1679077298882	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1679078412694	Sync.SyncScheduler	DEBUG	Going to sleep, doing a quick sync.
1679078412694	Sync.Service	DEBUG	User-Agent: Firefox/111.0 (Linux x86_64) FxSync/1.113.0.20230313175713.desktop
1679078412694	Sync.Service	INFO	Starting sync at 2023-03-17 18:40:12 in browser session pmulSksLPzeD
1679078412695	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1679078412696	Sync.Status	INFO	Resetting Status.
1679078412696	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1679078412696	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1679078412696	FirefoxAccounts	DEBUG	getOAuthToken enter
1679078412697	FirefoxAccounts	TRACE	getCachedToken returning cached token
1679078412697	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1679078412697	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1679092891393	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1679092891463	Sync.SyncScheduler	DEBUG	Woke from sleep.
1679092891463	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1679092891463	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1679092891464	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1679092891469	Sync.Service	DEBUG	User-Agent: Firefox/111.0 (Linux x86_64) FxSync/1.113.0.20230313175713.desktop
1679092891469	Sync.Service	INFO	Starting sync at 2023-03-17 22:41:31 in browser session pmulSksLPzeD
1679092891469	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:54:5) JS Stack trace: LockException@util.js:54:5
throwLockException@util.js:138:11
WrappedLock@util.js:152:15
_lockedSync@service.js:1372:6
sync/<@service.js:1336:18
WrappedCatch@util.js:123:27
sync@service.js:1337:7
1679092891469	Sync.Service	INFO	Cannot start sync: already syncing?
1679092893464	Sync.Service	DEBUG	User-Agent: Firefox/111.0 (Linux x86_64) FxSync/1.113.0.20230313175713.desktop
1679092893464	Sync.Service	INFO	Starting sync at 2023-03-17 22:41:33 in browser session pmulSksLPzeD
1679092893464	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:54:5) JS Stack trace: LockException@util.js:54:5
throwLockException@util.js:138:11
WrappedLock@util.js:152:15
_lockedSync@service.js:1372:6
sync/<@service.js:1336:18
WrappedCatch@util.js:123:27
sync@service.js:1337:7
1679092893464	Sync.Service	INFO	Cannot start sync: already syncing?
1679092896660	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1679092898402	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1679093185225	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"Aborting due to channel inactivity.\"  nsresult: \"0x804b000e (NS_ERROR_NET_TIMEOUT)\"  location: \"JS frame :: resource://services-common/rest.js :: abortTimeout :: line 387\"  data: no]"}
1679093185226	Sync.Resource	ERROR	Request timed out after 300000ms. Aborting.
1679093185227	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/204028242/info/collections failed: AbortError: The operation was aborted.  Stack trace: _doRequest/timeoutId<()@resource://services-sync/resource.js:189
notify()@resource://gre/modules/Timer.sys.mjs:49
1679093185227	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1679093185227	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1679093185227	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "Request aborted (timeout)"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "JS frame :: resource://services-sync/resource.js :: _doRequest :: line 199"  data: no] Stack trace: _doRequest()@resource://services-sync/resource.js:199
1679093185229	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1679093185233	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "Request aborted (timeout)"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "JS frame :: resource://services-sync/resource.js :: _doRequest :: line 199"  data: no] Stack trace: _doRequest()@resource://services-sync/resource.js:199
