1679044117748	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1679044117850	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile 304
1679044287720	Sync.SyncScheduler	DEBUG	Going to sleep, doing a quick sync.
1679044287720	Sync.Service	DEBUG	User-Agent: Firefox/111.0 (Linux x86_64) FxSync/1.113.0.20230313175713.desktop
1679044287720	Sync.Service	INFO	Starting sync at 2023-03-17 09:11:27 in browser session exRbB_1cn8GA
1679044287721	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1679044287724	Sync.Status	INFO	Resetting Status.
1679044287725	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1679044287725	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1679044287726	FirefoxAccounts	DEBUG	getOAuthToken enter
1679044287726	FirefoxAccounts	TRACE	getCachedToken returning cached token
1679044287726	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1679044287727	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1679046413424	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1679046413488	Sync.SyncScheduler	DEBUG	Woke from sleep.
1679046413488	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1679046413488	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1679046413489	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1679046415491	Sync.Service	DEBUG	User-Agent: Firefox/111.0 (Linux x86_64) FxSync/1.113.0.20230313175713.desktop
1679046415491	Sync.Service	INFO	Starting sync at 2023-03-17 09:46:55 in browser session exRbB_1cn8GA
1679046415491	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:54:5) JS Stack trace: LockException@util.js:54:5
throwLockException@util.js:138:11
WrappedLock@util.js:152:15
_lockedSync@service.js:1372:6
sync/<@service.js:1336:18
WrappedCatch@util.js:123:27
sync@service.js:1337:7
1679046415492	Sync.Service	INFO	Cannot start sync: already syncing?
1679046418666	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1679046419982	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1679046420038	Sync.Service	DEBUG	User-Agent: Firefox/111.0 (Linux x86_64) FxSync/1.113.0.20230313175713.desktop
1679046420038	Sync.Service	INFO	Starting sync at 2023-03-17 09:47:00 in browser session exRbB_1cn8GA
1679046420038	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:54:5) JS Stack trace: LockException@util.js:54:5
throwLockException@util.js:138:11
WrappedLock@util.js:152:15
_lockedSync@service.js:1372:6
sync/<@service.js:1336:18
WrappedCatch@util.js:123:27
sync@service.js:1337:7
1679046420039	Sync.Service	INFO	Cannot start sync: already syncing?
1679046424516	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile 304
1679046709850	Sync.Resource	ERROR	Request timed out after 300000ms. Aborting.
1679046709850	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/204028242/info/collections failed: AbortError: The operation was aborted.  Stack trace: _doRequest/timeoutId<()@resource://services-sync/resource.js:189
notify()@resource://gre/modules/Timer.sys.mjs:49
1679046709851	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1679046709851	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1679046709852	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "Request aborted (timeout)"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "JS frame :: resource://services-sync/resource.js :: _doRequest :: line 199"  data: no] Stack trace: _doRequest()@resource://services-sync/resource.js:199
1679046709854	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1679046709858	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "Request aborted (timeout)"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "JS frame :: resource://services-sync/resource.js :: _doRequest :: line 199"  data: no] Stack trace: _doRequest()@resource://services-sync/resource.js:199
